PersonalGPATracker/PersonalGPATracker/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PersonalGPATracker.Models
{
    public class Course
    {
        public string Code { get; set; }
        public string Title { get; set; }
        public int CreditHours { get; set; }
        public string LetterGrade { get; set; }
        public double GradePoints {
            get
            {
                var gradePoints = 0.0;
                switch (LetterGrade)
                {
                    case "A":
                        gradePoints = 4;
                        break;
                    case "A-":
                        gradePoints = 3.7;
                        break;
                    case "B+":
                        gradePoints = 3.3;
                        break;
                    case "B":
                        gradePoints = 3.0;
                        break;
                    case "B-":
                        gradePoints = 2.7;
                        break;
                    case "C+":
                        gradePoints = 2.3;
                        break;
                    case "C":
                        gradePoints = 2.0;
                        break;
                    case "C-":
                        gradePoints = 1.7;
                        break;
                    case "D+":
                        gradePoints = 1.3;
                        break;
                    case "D":
                        gradePoints = 1.0;
                        break;
                    case "F":
                    case "U":
                        gradePoints = 0.0;
                        break;
                }
                return gradePoints;
            }
        } // GradePoints

        public double QualityPoints
        {
            get
            {
                return CreditHours * GradePoints;
            }
        }
    }
}

PersonalGPATracker/PersonalGPATracker/Models/CourseList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PersonalGPATracker.Models
{
    public class CourseList
    {
        public List<Course> Courses { get; set; }

        public CourseList()
        {
            Courses = new List<Course>();
        }

        public double TotalQualityPoints
        {
            get
            {
                var total = 0.0;
                foreach(var course in Courses)
                {
                    total += course.QualityPoints;
                }
                return total;
            }
        }

        public double TotalCreditHours
        {
            get
            {
                var total = 0.0;
                foreach (var course in Courses)
                {
                    total += course.CreditHours;
                }
                return total;
            }
        }

        public double TotalGPA
        {
            get
            {
                if (TotalCreditHours == 0.0) return 0.0;
                return TotalQualityPoints / TotalCreditHours;
            }
        }
    }
}

PersonalGPATracker/PersonalGPATracker/Controllers/CourseController.cs
using PersonalGPATracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonalGPATracker.Controllers
{
    public class CourseController : Controller
    {
        private CourseList _courses = null;

        private void GetCourseList()
        {
            if (Session["CourseList"] != null)
            {
                _courses = (CourseList)Session["CourseList"];
            }
            else
            {
                _courses = new CourseList();
            }
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCourse(Course course)
        {
            GetCourseList();
            _courses.Courses.Add(course);
            Session["CourseList"] = _courses;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Edit(string id)
        {
            GetCourseList();
            var course = GetCourse(id);
            if(course == null)
            {
                return HttpNotFound(id + " was not found.");
            }
            return View(course);
        }

        [HttpPost]
        public ActionResult EditCourse(string oldCode, Course course)
        {
            GetCourseList();
            var oldCourse = GetCourse(oldCode);
            if (course == null)
            {
                View(course);
            }

            oldCourse.Code = course.Code;
            oldCourse.Title = course.Title;
            oldCourse.CreditHours = course.CreditHours;
            oldCourse.LetterGrade = course.LetterGrade;

            Session["CourseList"] = _courses;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Details(string id)
        {
            GetCourseList();
            var course = GetCourse(id);
            if (course == null)
            {
                return HttpNotFound(id + " was not found.");
            }
            return View(course);
        }

        public ActionResult Delete(string id)
        {
            GetCourseList();
            var course = GetCourse(id);
            if (course == null)
            {
                return HttpNotFound(id + " was not found.");
            }
            return View(course);
        }

        [HttpPost]
        public ActionResult DeleteCourse(string id)
        {
            GetCourseList();
            _courses.Courses.Remove(GetCourse(id));
            Session["CourseList"] = _courses;
            return RedirectToAction("Index", "Home");
        }

        private Course GetCourse(string code)
        {
            Course course = null;
            foreach(var c in _courses.Courses)
            {
                if(c.Code == code)
                {
                    course = c;
                    break;
                }
            }
            return course;
        }
    }
}

PersonalGPATracker/PersonalGPATracker/Controllers/HomeController.cs
using PersonalGPATracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonalGPATracker.Controllers
{
    public class HomeController : Controller
    {
        private CourseList _courses = null;

        private void GetCourseList()
        {
            if (Session["CourseList"] != null)
            {
                _courses = (CourseList)Session["CourseList"];
            }
            else
            {
                _courses = new CourseList();
            }
        }

        public ActionResult Index()
        {
            GetCourseList();
            return View(_courses);
        }

    }
}

PersonalGPATracker/PersonalGPATracker/Views/Course/Add.cshtml
@{
    ViewBag.Title = "Add New Course";
}

<h2>@ViewBag.Title</h2>


<form method="post" action="/course/addcourse">
    <div class="form-horizontal">

        <div class="form-group">
            <label for="Code" class="control-label col-md-2">Code:</label>
            <div class="col-md-10">
                <input type="text" id="Code" name="Code" class="form-control"/>
            </div>
        </div>

        <div class="form-group">
            <label for="Title" class="control-label col-md-2">Title:</label>
            <div class="col-md-10">
                <input type="text" id="Title" name="Title" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label for="CreditHours" class="control-label col-md-2">Credit Hours:</label>
            <div class="col-md-10">
                <select id="CreditHours" name="CreditHours" class="form-control">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="LetterGrade" class="control-label col-md-2">Letter Grade:</label>
            <div class="col-md-10">
                <select id="LetterGrade" name="LetterGrade" class="form-control">
                    <option value="A">A</option>
                    <option value="A-">A-</option>
                    <option value="B+">B+</option>
                    <option value="B">B</option>
                    <option value="B-">B-</option>
                    <option value="C+">C+</option>
                    <option value="C">C</option>
                    <option value="C-">C-</option>
                    <option value="D+">D+</option>
                    <option value="D">D</option>
                    <option value="F">F</option>
                    <option value="U">U</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Course" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to Course List", "Index", "Home")
</div>

PersonalGPATracker/PersonalGPATracker/Views/Course/Delete.cshtml
@model PersonalGPATracker.Models.Course

@{
    ViewBag.Title = "Delete course :" + Model.Code;
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Code:
        </dt>

        <dd>
            @Model.Code
        </dd>

        <dt>
            Title:
        </dt>

        <dd>
            @Model.Title
        </dd>

        <dt>
            Credit Hours:
        </dt>

        <dd>
            @Model.CreditHours
        </dd>

        <dt>
            Letter Grade:
        </dt>

        <dd>
            @Model.LetterGrade
        </dd>

    </dl>

    <form method="post" action="/course/deletecourse">
        <div class="form-actions no-color">
            <input type="hidden" name="id" value="@Model.Code"/>
            <input type="submit" value="Delete Course" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", "Home")
        </div>
    </form>
</div>

PersonalGPATracker/PersonalGPATracker/Views/Course/Details.cshtml
@model PersonalGPATracker.Models.Course

@{
    ViewBag.Title = "Details of course: " + Model.Code;
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Code:
        </dt>

        <dd>
            @Model.Code
        </dd>

        <dt>
            Title:
        </dt>

        <dd>
            @Model.Title
        </dd>

        <dt>
            Credit Hours:
        </dt>

        <dd>
            @Model.CreditHours
        </dd>

        <dt>
            Letter Grade:
        </dt>

        <dd>
            @Model.LetterGrade
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", "Course", new { id = Model.Code }, null) |
    @Html.ActionLink("Delete", "Delete", "Course", new { id = Model.Code }, null) |
    @Html.ActionLink("Back to Course List", "Index", "Home")
</p>

PersonalGPATracker/PersonalGPATracker/Views/Course/Edit.cshtml
@model PersonalGPATracker.Models.Course

@{
    ViewBag.Title = "Editing Course " + Model.Code;
}

<h2>@ViewBag.Title</h2>
<form method="post" action="/course/editcourse">
    <div class="form-horizontal">

        <input type="hidden" name="oldCode" value="@Model.Code"/>

        <div class="form-group">
            <label for="Code" class="control-label col-md-2">Code:</label>
            <div class="col-md-10">
                <input type="text" id="Code" name="Code" value ="@Model.Code" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label for="Title" class="control-label col-md-2">Title:</label>
            <div class="col-md-10">
                <input type="text" id="Title" name="Title" value ="@Model.Title" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label for="CreditHours" class="control-label col-md-2">Credit Hours:</label>
            <div class="col-md-10">
                <select id="CreditHours" name="CreditHours" value ="@Model.CreditHours" class="form-control">
                    @for (var option = 1; option <= 6; option++)
                    {
                        if (option != Model.CreditHours)
                        {
                            <option value="@option">@option</option>
                        }
                        else
                        {
                            <option value="@option" selected>@option</option>
                        }
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="LetterGrade" class="control-label col-md-2">Letter Grade:</label>
            <div class="col-md-10">
                <select id="LetterGrade" name="LetterGrade" value ="@Model.LetterGrade" class="form-control">
                    @{ 
                        string[] grades = {
                            "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "F", "U" };
                    }

                    @foreach (var grade in grades)
                    {
                        if (grade != Model.LetterGrade)
                        {
                            <option value="@grade">@grade</option>
                        }
                        else
                        {
                            <option value="@grade" selected>@grade</option>
                        }
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update Course" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to Course List", "Index", "Home")
</div>

PersonalGPATracker/PersonalGPATracker/Views/Home/Index.cshtml
@model PersonalGPATracker.Models.CourseList

@{
    ViewBag.Title = "Course List and GPA";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Add New Course", "Add", "Course")
</p>
<table class="table">
    <tr>
        <th>
            Code
        </th>
        <th>
            Title
        </th>
        <th>
            Credit Hours
        </th>
        <th>
            Letter Grade
        </th>
        <th>
            Grade Points
        </th>
        <th>
            Quality Points
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Courses) {
    <tr>
        <td>
            @item.Code
        </td>
        <td>
            @item.Title
        </td>
        <td>
            @item.CreditHours
        </td>
        <td>
            @item.LetterGrade
        </td>
        <td>
            @item.GradePoints
        </td>
        <td>
            @string.Format("{0:0.0}", item.QualityPoints)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Course", new { id=item.Code }, null) |
            @Html.ActionLink("Details", "Details", "Course", new { id = item.Code }, null) |
            @Html.ActionLink("Delete", "Delete", "Course", new { id = item.Code }, null)
        </td>
    </tr>
}

</table>

<h1>Total GPA: @string.Format("{0:0.00}", Model.TotalGPA)</h1>

PersonalGPATracker/PersonalGPATracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Personal GPA Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add Course", "Add", "Course")</li>
                    <li><a href="">Jeff Roach</a></li>
                    <li><a href="mailto:roachj@etsu.edu">roachj@etsu.edu</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>